name: Go build

run-name: >
  Build Go Service — ${{ github.event_name }}
  (${{ github.head_ref || github.ref_name }})
  [${{ github.event_name == 'push' && format('— {0}', github.event.head_commit.message) || '' }}
  ${{ github.event_name == 'pull_request' && format('— {0}', github.event.pull_request.title) || '' }}]

on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-go-service:
    uses: taurmorchant/workflows-test/.github/workflows/build-go-service.yaml@main
    with:
      actor: ${{ github.actor }}
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}